# Generated by Django 5.0 on 2024-01-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexaBlog', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='User',
        ),
    ]
